# Setup
title:               Novedades streaming blog
tagline:             'Tu blog de los lanzamientos y noticias de plataformas de streaming'
description:         'Lectura obligada para estar al día con los lanzamientos de peliculas,series y documentales de Netflix en España.'
url:                 https://blog.novedades-streaming.com/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Miguel Molina
  url:               https://github.com/molidestroyer/novedadesstreamingblog
  email:             chollolocura@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

