# Setup
title:               Novedades streaming blog
tagline:             'Tus noticias de plataformas de streaming'
description:         'Lectura obligada para estar al día con los lanzamientos de peliculas,series y documentales de Netflix en España.'
titlesidebar:        'Lanzamientos streaming'
url:                 https://blog.novedades-streaming.com/
paginate:            5
permalink:           pretty
locale:              es_es

# About/contact
author:
  name:              Miguel Molina
  profile_github:    https://github.com/molidestroyer/novedadesstreamingblog
  email:             miguel.molina.montilla@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-164784429-1
